version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.15.1

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0e:e8:97:aa:ee:44:6f:26:b8:8a:b5:79:bd:d4:b8:47"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "mohithgm@gmail.com"
            git config --global user.name "mohithg"
            npm install
            npm install gh-pages --save-dev
            npm run deploy
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - /releases-.*-next/